package com.parkspace.finder.navigation

const val ROUTE_LOGIN = "login"
const val ROUTE_SIGNUP = "signup"
const val ROUTE_HOME = "home"
const val ROUTE_PAYMENT = "payment"
const val ROUTE_PAYMENT_SUCCESS = "payment_success"
const val ROUTE_BOOKING_SERVICE = "booking_service"
const val ROUTE_ENTER_BOOKING_DETAIL_SCREEN= "parking/{parkingId}/book"
const val ROUTE_PARKING_TICKET = "parking_ticket_booked"
const val ROUTE_BROWSE = "browse"
const val ROUTE_BOOKINGS = "bookings"
const val ROUTE_FAVORITES = "favorites"
const val ROUTE_NOTIFICATIONS = "notifications"
const val ROUTE_ACCOUNT = "account"
const val ROUTE_PARKING_DETAIL = "parking_detail"
const val ROUTE_ONBOARDING = "onboarding"
const val ROUTE_REQUEST_LOCATION_PERMISSION = "request_location_permission"
const val ROUTE_FILTER = "filter"
const val ROUTE_SEARCH = "search"
